version: '3.8'

networks:
  default:
    name: uxm-music

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  db:
    image: mysql:8.0.29
    container_name: uxm-music-mysql
    ports:
      - 3310:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
      - ./mysql-init-files/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: uxmusic
    platform: linux/x86_64
    restart: always

  db-admin-web:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: uxm-music-mysqladmin
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysql
    platform: linux/x86_64
    restart: always